# Generated by Django 4.1.4 on 2022-12-24 01:24

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='description',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.RemoveField(
            model_name='polls',
            name='options',
        ),
        migrations.AddField(
            model_name='polls',
            name='options',
            field=models.ManyToManyField(to='polls.options'),
        ),
    ]
